//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceavitProDesktop.assets {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraceavitProDesktop.assets.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевірено.
        /// </summary>
        public static string CheckWorkspaceView_Button_Content {
            get {
                return ResourceManager.GetString("CheckWorkspaceView.Button.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будь ласка, зверніть увагу на те, 
        ///щоб на робочому місці не було зайвих предметів.
        /// </summary>
        public static string CheckWorkspaceView_Text {
            get {
                return ResourceManager.GetString("CheckWorkspaceView.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевірте робоче місце.
        /// </summary>
        public static string CheckWorkspaceView_TopAppBar_Title {
            get {
                return ResourceManager.GetString("CheckWorkspaceView.TopAppBar.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дякуємо за роботу!.
        /// </summary>
        public static string EndWorkCompleteView_TextBlock1_Text {
            get {
                return ResourceManager.GetString("EndWorkCompleteView.TextBlock1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша зміна завершена.
        ///Бажаємо вам гарного завершення дня.
        /// </summary>
        public static string EndWorkCompleteView_TextBlock2_Text {
            get {
                return ResourceManager.GetString("EndWorkCompleteView.TextBlock2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Підтвердити.
        /// </summary>
        public static string EndWorkConfirmErrorView_Button1_Content {
            get {
                return ResourceManager.GetString("EndWorkConfirmErrorView.Button1.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виправити.
        /// </summary>
        public static string EndWorkConfirmErrorView_Button2_Content {
            get {
                return ResourceManager.GetString("EndWorkConfirmErrorView.Button2.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задекларована кількість 5 палет та 15 каністр не збігається з фактичною кількістю.
        /// </summary>
        public static string EndWorkConfirmErrorView_TextBlock1_Text {
            get {
                return ResourceManager.GetString("EndWorkConfirmErrorView.TextBlock1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевірте та виправте актуальну кількість або підтвердіть, що наведена кількість вірна.
        /// </summary>
        public static string EndWorkConfirmErrorView_TextBlock2_Text {
            get {
                return ResourceManager.GetString("EndWorkConfirmErrorView.TextBlock2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Підтверджую.
        /// </summary>
        public static string EndWorkConfirmView_Button1_Content {
            get {
                return ResourceManager.GetString("EndWorkConfirmView.Button1.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ввести інше.
        /// </summary>
        public static string EndWorkConfirmView_Button2_Content {
            get {
                return ResourceManager.GetString("EndWorkConfirmView.Button2.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Промарковано палет:.
        /// </summary>
        public static string EndWorkConfirmView_TextBlock1_Text {
            get {
                return ResourceManager.GetString("EndWorkConfirmView.TextBlock1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Промаркованої тари на палеті:.
        /// </summary>
        public static string EndWorkConfirmView_TextBlock2_Text {
            get {
                return ResourceManager.GetString("EndWorkConfirmView.TextBlock2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уважно порахуйте кількість товару на палеті.
        ///У разі неспівпадіння змініть кількість на актуальну кнопкою нижче.
        /// </summary>
        public static string EndWorkConfirmView_TextBlock3_Text {
            get {
                return ResourceManager.GetString("EndWorkConfirmView.TextBlock3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершення роботи.
        /// </summary>
        public static string EndWorkConfirmView_TopAppBar_Title {
            get {
                return ResourceManager.GetString("EndWorkConfirmView.TopAppBar.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Підтверджую.
        /// </summary>
        public static string EndWorkCountProductView_Button_Content {
            get {
                return ResourceManager.GetString("EndWorkCountProductView.Button.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть кількість.
        /// </summary>
        public static string EndWorkCountProductView_TextBox_Hint {
            get {
                return ResourceManager.GetString("EndWorkCountProductView.TextBox.Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть кількість промаркованої тари на палеті.
        /// </summary>
        public static string EndWorkCountProductView_TopAppBar_Title {
            get {
                return ResourceManager.GetString("EndWorkCountProductView.TopAppBar.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор - лайблер.
        /// </summary>
        public static string JobProcessViewModel_JobProcessViewModel_Labeler {
            get {
                return ResourceManager.GetString("JobProcessViewModel_JobProcessViewModel_Labeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор - пакер.
        /// </summary>
        public static string JobProcessViewModel_JobProcessViewModel_Packer {
            get {
                return ResourceManager.GetString("JobProcessViewModel_JobProcessViewModel_Packer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ласкаво просимо!.
        /// </summary>
        public static string LoginViewMsg1 {
            get {
                return ResourceManager.GetString("LoginViewMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для продовження вiдскануйте свою карту доступу!.
        /// </summary>
        public static string LoginViewMsg2 {
            get {
                return ResourceManager.GetString("LoginViewMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виклик майстра.
        /// </summary>
        public static string PauseReasonView_ButtonCallMaster_Content {
            get {
                return ResourceManager.GetString("PauseReasonView.ButtonCallMaster.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перерва.
        /// </summary>
        public static string PauseReasonView_ButtonDinner_Content {
            get {
                return ResourceManager.GetString("PauseReasonView.ButtonDinner.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Налагодження обладнання.
        /// </summary>
        public static string PauseReasonView_ButtonEquipmentSetup_Content {
            get {
                return ResourceManager.GetString("PauseReasonView.ButtonEquipmentSetup.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Несправність.
        /// </summary>
        public static string PauseReasonView_ButtonFault_Content {
            get {
                return ResourceManager.GetString("PauseReasonView.ButtonFault.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продовжити.
        /// </summary>
        public static string PauseReasonView_ButtonNext_Content {
            get {
                return ResourceManager.GetString("PauseReasonView.ButtonNext.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оберіть причину зупинки.
        /// </summary>
        public static string PauseReasonView_TopAppBar_Title {
            get {
                return ResourceManager.GetString("PauseReasonView.TopAppBar.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Триває призупинення роботи.
        /// </summary>
        public static string PauseStopProcessView_TextBlock1_Text {
            get {
                return ResourceManager.GetString("PauseStopProcessView.TextBlock1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будь ласка, зачекайте.
        /// </summary>
        public static string PauseStopProcessView_TextBlock2_Text {
            get {
                return ResourceManager.GetString("PauseStopProcessView.TextBlock2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Підтверджую.
        /// </summary>
        public static string PrintActualCountProductView_Button_Content {
            get {
                return ResourceManager.GetString("PrintActualCountProductView.Button.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть кількість.
        /// </summary>
        public static string PrintActualCountProductView_TextBox_Hint {
            get {
                return ResourceManager.GetString("PrintActualCountProductView.TextBox.Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть актуальну кількість товару.
        /// </summary>
        public static string PrintActualCountProductView_TopAppBar_Title {
            get {
                return ResourceManager.GetString("PrintActualCountProductView.TopAppBar.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Надрукувати.
        /// </summary>
        public static string PrintCloseBoxView_ButtonLeft_Content {
            get {
                return ResourceManager.GetString("PrintCloseBoxView.ButtonLeft.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Змінити кількість товару.
        /// </summary>
        public static string PrintCloseBoxView_ButtonRight_Content {
            get {
                return ResourceManager.GetString("PrintCloseBoxView.ButtonRight.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кількість товару в ящику:.
        /// </summary>
        public static string PrintCloseBoxView_TextBlock1_Text {
            get {
                return ResourceManager.GetString("PrintCloseBoxView.TextBlock1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уважно порахуйте кількість товару в ящику.
        ///У разі неспівпадіння змініть кількість на актуальну кнопкою нижче .
        /// </summary>
        public static string PrintCloseBoxView_TextBlock2_Text {
            get {
                return ResourceManager.GetString("PrintCloseBoxView.TextBlock2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закриття ящика.
        /// </summary>
        public static string PrintCloseBoxView_TopAppBar_Title {
            get {
                return ResourceManager.GetString("PrintCloseBoxView.TopAppBar.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Надрукувати.
        /// </summary>
        public static string PrintClosePalleteView_ButtonLeft_Content {
            get {
                return ResourceManager.GetString("PrintClosePalleteView.ButtonLeft.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Змінити кількість товару.
        /// </summary>
        public static string PrintClosePalleteView_ButtonRight_Content {
            get {
                return ResourceManager.GetString("PrintClosePalleteView.ButtonRight.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кількість товару на палеті:.
        /// </summary>
        public static string PrintClosePalleteView_TextBlock1_Text {
            get {
                return ResourceManager.GetString("PrintClosePalleteView.TextBlock1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уважно порахуйте кількість товару на палеті.
        ///У разі неспівпадіння змініть кількість на актуальну кнопкою нижче.
        /// </summary>
        public static string PrintClosePalleteView_TextBlock2_Text {
            get {
                return ResourceManager.GetString("PrintClosePalleteView.TextBlock2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закриття палети.
        /// </summary>
        public static string PrintClosePalleteView_TopAppBar_Title {
            get {
                return ResourceManager.GetString("PrintClosePalleteView.TopAppBar.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Триває друк етикетки.
        /// </summary>
        public static string PrintProgressView_TextBlock1_Text {
            get {
                return ResourceManager.GetString("PrintProgressView.TextBlock1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будь ласка, зачекайте.
        /// </summary>
        public static string PrintProgressView_TextBlock2_Text {
            get {
                return ResourceManager.GetString("PrintProgressView.TextBlock2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Надрукувати.
        /// </summary>
        public static string PrintRepeatView_Button_Content {
            get {
                return ResourceManager.GetString("PrintRepeatView.Button.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пошук номеру етикетки.
        /// </summary>
        public static string PrintRepeatView_SearchBox_Hint {
            get {
                return ResourceManager.GetString("PrintRepeatView.SearchBox.Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторний друк.
        /// </summary>
        public static string PrintRepeatView_TopAppBar_Title {
            get {
                return ResourceManager.GetString("PrintRepeatView.TopAppBar.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відскануйте QR код лінії.
        /// </summary>
        public static string ScanLineView_Msg {
            get {
                return ResourceManager.GetString("ScanLineView.Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відскануйте QR код лінії за допомогою ручного сканера.
        /// </summary>
        public static string ScanLineViewBackMsg {
            get {
                return ResourceManager.GetString("ScanLineViewBackMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск.
        /// </summary>
        public static string ShiftRunView_TextBlock1_Text {
            get {
                return ResourceManager.GetString("ShiftRunView.TextBlock1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будь ласка, зачекайте.
        /// </summary>
        public static string ShiftRunView_TextBlock2_Text {
            get {
                return ResourceManager.GetString("ShiftRunView.TextBlock2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почати зміну.
        /// </summary>
        public static string ShiftStartView_ButtonLeft_Content {
            get {
                return ResourceManager.GetString("ShiftStartView.ButtonLeft.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Налагоджувальна зміна.
        /// </summary>
        public static string ShiftStartView_ButtonRight_Content {
            get {
                return ResourceManager.GetString("ShiftStartView.ButtonRight.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бажаю вам успішного та продуктивного робочого дня!.
        /// </summary>
        public static string ShiftStartView_TextBlock1_Text {
            get {
                return ResourceManager.GetString("ShiftStartView.TextBlock1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нехай кожен крок приносить вам набагато більше, ніж ви очікуєте! Вперед до нових вершин!.
        /// </summary>
        public static string ShiftStartView_TextBlock2_Text {
            get {
                return ResourceManager.GetString("ShiftStartView.TextBlock2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готові почати зміну?.
        /// </summary>
        public static string ShiftStartView_TopAppBar_Title {
            get {
                return ResourceManager.GetString("ShiftStartView.TopAppBar.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гарного робочого дня.
        /// </summary>
        public static string WelcomeViewMsg {
            get {
                return ResourceManager.GetString("WelcomeViewMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша карта доступу успiшно просканована.
        /// </summary>
        public static string WelcomeViewMsg2 {
            get {
                return ResourceManager.GetString("WelcomeViewMsg2", resourceCulture);
            }
        }
    }
}
